services:
  marzban:
    image: ghcr.io/spaik111/vpn-service:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban

  telegram-bot:
    image: ghcr.io/spaik111/vpn-service-bot:latest
    restart: always
    env_file: bot.env
    network_mode: host
    volumes:
      - /var/lib/marzban-bot:/data
