services:
  remnanode:
    container_name: remnanode
    hostname: remnanode
    image: remnawave/node:latest
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    env_file: node.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/remnawave/xray/share/zapret.dat:/usr/local/bin/zapret.dat:ro
